---

# vars file for rabbitmq test
rabbitmq_vhost_definitions:
  - sensu

rabbitmq_users_definitions:
  - vhost   : sensu
    user    : sensu
    password: placeholder

rabbitmq_ssl: false

rabbitmq_federation: false

rabbitmq_federation_configuration:
  - name: test
    vhost: '/'
    value: '{"uri":"amqp://server-name","expires":3600000}'
    local_username: sensu

rabbitmq_policy_configuration:
  - name: policy
    pattern: '.'
    vhost: sensu
    tags: "federation-upstream-set=all"
